### ISSUE TITLE
Doesn't parse Blink/WebKit/Gecko's "canonical" format

### ISSUE THREAD

**Issue by cvrebert** [mrrrgn/proposal-date-time-string-format#8]
Example: `Thu May 26 1988 01:01:23 GMT-0700 (PDT)`
(Canonical in the sense that it's what you get when you stringify a `Date` object.)

**Comment by mrrrgn** [comment]
Oooh, very nice format to add. Thank you!

**Comment by cpeterso** [comment]
IE/Edge's Date string representation looks like `Thu May 26 1988 01:01:23 GMT-0700 (Pacific Daylight Time)` (same as above except "PDT" is expanded to "Pacific Daylight Time").

**Comment by mrrrgn** [comment]
Fixed in c509bff5e4c60242e44ec3f66a2ba3380b118f03

**Comment by cvrebert** [comment]
@mrrrgn I'm still seeing Invalid Date, even after clearing my browser's cache.
